theme: minima
title: Home
description: A community of Nextflow ecologists
url: "https://eco-flow.github.io"

plugins:
  - jekll-feed
  - jekyll-titles-from-headings

author: Chris Wyatt
twitter_username: Wyatt1Chris
email: c.wyatt@ucl.ac.uk

header_pages:
  - about.md
  - partners.md
  - pipelines.md
  - services.md
  - citations.md
