theme: minima
title: Home
description: A community of Nextflow ecologists
url: "https://eco-flow.github.io"

plugins:
  -jekll-feed

author: Chris Wyatt

header_pages:
  - about.md
  - partners.md
  - pipelines.md
  - services.md
  - citations.md
