theme: minima
title: Home
description: A community of computational agri-ecologists
url: "https://eco-flow.github.io"

plugins:
  - jekll-feed
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

authors: Chris Wyatt, Simon Muray
email: ecoflow . ucl AT gmail . com

header_pages:
  - about.md
  - partners.md
  - pipelines.md
  - services.md
  - citations.md
